version: 1.0.{build}
branches:
  only:
  - develop
  - feature-173
image: Ubuntu
environment:
  my_variable:
    secure: +GIXChQeD2YvKKJfsC32mG4tVbbM49BK243gEJwayyB1IO98plDBc6wJ/yIQfG2XoSDaqgFtNbW/utfCN+D0rA==
install:
  - sh: sudo export QTDIR=$HOME/Qt/5.15.2
  - sh: sudo ls $HOME/Qt/5.15.2
  - sh: sudo ls $HOME/Qt/5.15.2/gcc_64/bin
  - sh: sudo export PATH=$QTDIR/bin:$HOME/Qt/5.15.2/gcc_64/bin:$PATH
  - sh: sudo set -euo pipefail
  - sh: sudo buildDirPath=$HOME/build
  - sh: sudo mkdir -p $buildDirPath
  - sh: sudo apt update
  - sh: sudo apt install fuse
  - sh: sudo apt-get install libdrm-dev
  - sh: sudo apt-get install libtinfo-dev 
  - sh: sudo apt-get install libgl1-mesa-dev -y
  - sh: sudo apt-get install -f
configuration: Release
before_build:
  - sh: sudo qmake PREFIX=$buildDirPath Seamly2D.pro -r CONFIG+=no_ccache CONFIG+=noDebugSymbols
  - sh: sudo make
  - sh: sudo make install   
build:
  parallel: true 
  verbosity: normal
after_build:
  - sh: sudo mkdir -p $buildDirPath/{share/applications,share/icons/hicolor/256x256,share/translations}
  - sh: sudo cp dist/seamly2d.desktop $buildDirPath/share/applications
  - sh: sudo cp share/img/Seamly2D_logo_256x256.png $buildDirPath/share/icons/hicolor/256x256/seamly2d.png
  - sh: sudo cp share/translations/*.qm $buildDirPath/share/translations
  - sh: sudo cp src/app/seamlyme/bin/diagrams.rcc $buildDirPath/share
  - sh: sudo docker run --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined --security-opt seccomp=unconfined -v $buildDirPath:/app/usr -e EXTRA_BINARIES="seamlyme" --rm mhitza/linuxdeployqt:"$QT_VERSION"
  - sh: sudo mv $buildDirPath/Seamly2D*.AppImage Seamly2D.AppImage
