version: 1.0.{build}
branches:
  only:
  - develop
image: Ubuntu
environment:
  my_variable:
    secure: +GIXChQeD2YvKKJfsC32mG4tVbbM49BK243gEJwayyB1IO98plDBc6wJ/yIQfG2XoSDaqgFtNbW/utfCN+D0rA==
install:
  - sh: export QTDIR=$HOME/Qt/5.15.2
  - sh: export PATH=$QTDIR/bin:$PATH
  - sh: set -euo pipefail
  - sh: readonly buildDirPath=/home/runner/local
  - sh: mkdir $buildDirPath
  - sh: sudo apt update
  - sh: sudo apt install fuse
  - sh: sudo apt-get install libdrm-dev
  - sh: sudo apt-get install -f
configuration: Release
before_build:
  - sh: qmake PREFIX=$buildDirPath Seamly2D.pro -r CONFIG+=no_ccache CONFIG+=noDebugSymbols
  - sh: make
  - sh: make install   
build:
  parallel: true 
  verbosity: normal
after_build:
  - sh: mkdir -p $buildDirPath/{share/applications,share/icons/hicolor/256x256,share/translations}
  - sh: cp dist/seamly2d.desktop $buildDirPath/share/applications
  - sh: cp share/img/Seamly2D_logo_256x256.png $buildDirPath/share/icons/hicolor/256x256/seamly2d.png
  - sh: cp share/translations/*.qm $buildDirPath/share/translations
  - sh: cp src/app/seamlyme/bin/diagrams.rcc $buildDirPath/share
  - sh: docker run --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined --security-opt seccomp=unconfined -v $buildDirPath:/app/usr -e EXTRA_BINARIES="seamlyme" --rm mhitza/linuxdeployqt:"$QT_VERSION"
  - sh: mv $buildDirPath/Seamly2D*.AppImage Seamly2D.AppImage
