name: CI
# DOES NOT CREATE A RELEASE - builds Seamly2D Windows application, macOS DMG and AppImage and attaches to GH action run, runs unit tests on linux
# DOES NOT TEST SEAMLYME.EXE

# Trigger on pull requests before merge
on: [ pull_request ]

env:
  QT_VERSION: '5.15.2' # quotes required or YAML parser will interpret as float

jobs:

  build-appimage:
    name: 'Linux: Build AppImage'
    runs-on: ubuntu-18.04  # build on the oldest supported LTS so that resulting binaries are compatible with older and newer Linux releases

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install appimage dependencies
        run: |
          sudo apt update && sudo apt install -y libfuse2
          sudo wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -O /usr/local/bin/linuxdeploy-x86_64.AppImage
          sudo chmod +x /usr/local/bin/linuxdeploy-x86_64.AppImage
          sudo wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage -O /usr/local/bin/linuxdeploy-plugin-qt-x86_64.AppImage
          sudo chmod +x /usr/local/bin/linuxdeploy-plugin-qt-x86_64.AppImage

      - name: install qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          cache: true

      - name: build Seamly2D appimage
        env:
          OUTPUT: Seamly2D-x86_64.AppImage
        run: |
          qmake -config release CONFIG+=noDebugSymbols CONFIG+=noTests
          make -j$(nproc)
          make INSTALL_ROOT=`pwd`/AppDir install
          # install poppler-utils for pdftops, gstreamer1.0-plugins-base for QtMultimedia
          sudo apt update && sudo apt install -y poppler-utils gstreamer1.0-plugins-base
          cp /usr/bin/pdftops AppDir/usr/bin
          linuxdeploy-x86_64.AppImage --appdir AppDir --desktop-file=dist/seamly2d.desktop --plugin qt --output appimage

      - name: Upload Seamly2D-x86_64.AppImage artifact
        # upload Seamly2D-x86_64.AppImage as artifact to Github Workflows
        uses: actions/upload-artifact@v3
        with:
          name: Seamly2D-x86_64.AppImage
          path: Seamly2D-x86_64.AppImage

  build-linux-test:
    name: 'Linux: Run unit tests'
    runs-on: ubuntu-18.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          cache: true

      - name: build Seamly2D & SeamlyMe for tests
        run: |
          qmake Seamly2D.pro
          make -j$(nproc)

      - name: install test dependencies
        # xvfb use to test built application within a framebuffer
        run: |
          sudo apt update
          sudo apt install -y xvfb

      # run the tests
      - name: test Seamly2D.exe
        run: |
          xvfb-run -a make check

  build-windows:
    name: 'Windows: Build'
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          # use Visual C++ 2022 latest, 14.34.xxxx
          toolset: '14.34'

      - name: install qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          cache: true

      - name: make seamly2d.exe and seamlyme.exe
        run: |
          qmake.exe Seamly2D.pro -config release CONFIG+=noDebugSymbols CONFIG+=noTests
          nmake

      - name: create seamly2d-installer.exe
        # copy seamly2d and seamlyme directory trees prepared by windeployqt and create installer
        # uses parameters in seamly2d-installer.nsi to create the installer exe
        run: |
          mkdir ..\windows-build
          Copy-Item -Path 'src\app\seamly2d\bin\*' -Destination ..\windows-build -Recurse
          Copy-Item -Path 'src\app\seamlyme\bin\*' -Destination ..\windows-build -Recurse -Force
          Copy-Item -Path dist\seamly2d-installer.nsi -Destination ..\windows-build
          cd ..\windows-build\
          & 'C:\Program Files (x86)\NSIS\makensis.exe' seamly2d-installer.nsi

      - name: pack installer file into .zip
        run: |
          cd ..\windows-build\
          C:\"Program Files"\7-Zip\7z.exe a Seamly2D-windows.zip Seamly2D-installer.exe
          copy Seamly2D-windows.zip ..\Seamly2D\

      - name: Upload Seamly2D-windows.zip artifact
        # upload Seamly2D-windows.zip as artifact to Github Workflows
        uses: actions/upload-artifact@v3
        with:
          name: Seamly2D-windows.zip
          path: Seamly2D-windows.zip

  build-macos:
    name: 'macOS: Build'
    runs-on: macos-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          cache: true

      - name: make Seamly2D for macos
        run: |
          qmake Seamly2D.pro -config release CONFIG+=noDebugSymbols CONFIG+=noTests
          make -j$(sysctl -n hw.logicalcpu)

      - name: Upload Seamly2D-macos.zip artifact
        # upload Seamly2D-installer.exe as artifact to Github Workflows
        uses: actions/upload-artifact@v3
        with:
          name: Seamly2D-macos.zip
          path: out/Seamly2D-macos.zip
