name: Build appimage - manual

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Build appimage - manual'

env:
  UPLOAD_URL: ${{ github.event.release.upload_url }} 
  QT_SELECT: 5
  QT_VERSION: '5.15.3' # quotes required or YAML parser will interpret as float

jobs:
  linux:
    runs-on: ubuntu-20.04  
    outputs:
      version: ${{ steps.step_version.outputs.version }}
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}

        
    steps:
      - id: step_version
        run: echo "::set-output name=version::${{ steps.package_version.outputs.version }}"
        
      - id: step_upload_url 
        run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"
      
      - uses: actions/checkout@v2.3.5
      
      - name: Install Qt5
        run: |
          # register kde neon repository
          echo 'deb http://archive.neon.kde.org/user focal main' | sudo tee /etc/apt/sources.list.d/neon.list
          curl https://origin.archive.neon.kde.org/public.key -o - | sudo apt-key add -
          # install build dependencies
          sudo apt-get update
          sudo apt-get install -y build-essential gettext git qt5-default qttools5-dev libqt5svg5-dev libqt5xmlpatterns5-dev
          sudo apt-get install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
          
      - name: build
        run: |
          sudo wget -q https://github.com/AppImageCrafters/appimage-builder/releases/download/v0.8.8/appimage-builder-0.8.8-4e7c15f-x86_64.AppImage -O /usr/local/bin/appimage-builder
          sudo chmod +x /usr/local/bin/appimage-builder
          appimage-builder --recipe .github/workflows/appimage-recipe.yml --skip-test
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: Seamly2D-x86_64.AppImage
          path: './*.AppImage*'
          
      - name: upload Seamly2D-x86_64.AppImage
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.Make_GitHub_Release.outputs.upload_url }}
          asset_path: ./Seamly2D-x86_64.AppImage
          asset_name: Seamly2D-x86_64.AppImage
          asset_content_type: application/octet-stream

