name: Test on push

on: [ push ]

env:
  QT_SELECT: 5
  QT_VERSION: '5.15.2' # quotes required or YAML parser will interpret as float

jobs:
  build-test:
    name: 'Build & Test Qt build'
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.5

      - name: install qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: ${{ env.QT_VERSION }}

      - name: install kde and dependencies
        run: |
          # register kde neon repository
          echo 'deb http://archive.neon.kde.org/user focal main' | sudo tee /etc/apt/sources.list.d/neon.list
          curl https://origin.archive.neon.kde.org/public.key -o - | sudo apt-key add -
          # install build dependencies
          sudo apt update
          sudo apt install -y build-essential gettext git qt5-default qttools5-dev libqt5svg5-dev libqt5xmlpatterns5-dev
          sudo apt install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
          sudo apt install -y libdrm-dev

      - name: build Seamly2D.exe
        run: |
          mkdir /home/runner/local
          qmake PREFIX=/home/runner/local Seamly2D.pro -r CONFIG+=no_ccache
          make -j$(nproc) && make install

      - name: install test dependencies
        # xvfb use to test built application within a framebuffer
        run: |
          sudo apt update
          sudo apt install -y xvfb

      - name: test Seamly2D.exe
        run: |
          export LD_LIBRARY_PATH=/home/runner/local/lib64/Seamly2D
          xvfb-run -a make --silent check TESTARGS="-silent"
